### ISSUE TITLE
Faltan eventos en Comscore

### ISSUE THREAD

**Issue by rodowi** [mxabierto/participa#205]
- [x] flagging de comentarios #207
- [x] el envío de **sub**comentarios #208
- [x] likes y dislikes de annotations #209

Notas:
- Los comentarios a primer nivel sí se registran.
